INSERT INTO logs (user_id, username, created_at, type, content, other, model_name, token_name, channel_id, channel_name, `group`, ip) VALUES
(1, 'testuser1', UNIX_TIMESTAMP(NOW() - INTERVAL 45 SECOND), 5, '429 error simulation', 'InvokeModelWithResponseStream: operation error Bedrock Runtime: InvokeModelWithResponseStream, exceeded maximum number of attempts, 3, https response error StatusCode: 429, RequestID: 3216d02f-a6e6-4a9d-9c7c-308e9a617e42', 'gpt-4', 'test-token-1', 1, 'test', 'default', '127.0.0.1'),
(2, 'testuser2', UNIX_TIMESTAMP(NOW() - INTERVAL 40 SECOND), 5, '429 error simulation', 'InvokeModel: operation error Bedrock Runtime: InvokeModel, https response error StatusCode: 429, RequestID: abc123-def456', 'gpt-4', 'test-token-2', 1, 'test', 'default', '127.0.0.1'),
(1, 'testuser3', UNIX_TIMESTAMP(NOW() - INTERVAL 35 SECOND), 5, '429 error simulation', 'InvokeModelWithResponseStream: Rate limit exceeded, StatusCode: 429, RequestID: xyz789-uvw012', 'gpt-4', 'test-token-3', 1, 'test', 'default', '127.0.0.1'),
(3, 'testuser4', UNIX_TIMESTAMP(NOW() - INTERVAL 30 SECOND), 5, '429 error simulation', 'ThrottlingException: Rate exceeded, StatusCode: 429, RequestID: test-id-001', 'gpt-4', 'test-token-4', 1, 'test', 'default', '127.0.0.1'),
(1, 'testuser5', UNIX_TIMESTAMP(NOW() - INTERVAL 25 SECOND), 5, '429 error simulation', 'InvokeModel: Too many requests, StatusCode: 429, RequestID: test-id-002', 'gpt-4', 'test-token-5', 1, 'test', 'default', '127.0.0.1'),
(2, 'testuser6', UNIX_TIMESTAMP(NOW() - INTERVAL 20 SECOND), 5, '429 error simulation', 'InvokeModelWithResponseStream: Service quota exceeded, StatusCode: 429, RequestID: test-id-003', 'gpt-4', 'test-token-6', 1, 'test', 'default', '127.0.0.1'),
(1, 'testuser7', UNIX_TIMESTAMP(NOW() - INTERVAL 15 SECOND), 5, '429 error simulation', 'InvokeModel: Request throttled, StatusCode: 429, RequestID: test-id-004', 'gpt-4', 'test-token-7', 1, 'test', 'default', '127.0.0.1'),
(4, 'testuser8', UNIX_TIMESTAMP(NOW() - INTERVAL 10 SECOND), 5, '429 error simulation', 'InvokeModelWithResponseStream: Concurrent request limit exceeded, StatusCode: 429, RequestID: test-id-005', 'gpt-4', 'test-token-8', 1, 'test', 'default', '127.0.0.1'),
(2, 'testuser9', UNIX_TIMESTAMP(NOW() - INTERVAL 5 SECOND), 5, '429 error simulation', 'InvokeModel: Model overloaded, StatusCode: 429, RequestID: test-id-006', 'gpt-4', 'test-token-9', 1, 'test', 'default', '127.0.0.1'),
(1, 'testuser10', UNIX_TIMESTAMP(NOW()), 5, '429 error simulation', 'InvokeModelWithResponseStream: Temporary service limit exceeded, StatusCode: 429, RequestID: test-id-007', 'gpt-4', 'test-token-10', 1, 'test', 'default', '127.0.0.1');
